spring:
  application:
    name: ConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hsharif269:299Rainbow!/application-config
eureka:
  client:
    region: default
    register-with-eureka: true
    service-url: http://localhost:8761/eureka


test:
  var: I am testing.
